<?php
use yii\helpers\ArrayHelper;

$params = ArrayHelper::merge(
    require __DIR__ . '/../../common/config/params.php',
    require __DIR__ . '/params.php'
);

return [
    'id'                  => 'hudumalynk-backend',
    'basePath'            => dirname(__DIR__),
    'bootstrap'           => ['log'],
    'controllerNamespace' => 'backend\controllers',
    'defaultRoute'        => 'site/index',
    'components' => [
        'request' => [
            'csrfParam' => '_csrf-backend',
            'cookieValidationKey' => $_ENV['APP_KEY'] ?? 'fallback-key-backend',
            'baseUrl'   => '',
        ],
        'user' => [
            'identityClass'   => 'common\models\User',
            'enableAutoLogin' => true,
            'identityCookie'  => ['name' => '_identity-backend', 'httpOnly' => true],
            'loginUrl'        => ['/site/login'],
        ],
        'session' => [
            'name' => 'hudumalynk-backend-session',
        ],
        'log' => [
            'traceLevel' => YII_DEBUG ? 3 : 0,
            'targets' => [[
                'class'   => 'yii\log\FileTarget',
                'levels'  => ['error', 'warning'],
                'logFile' => '@backend/runtime/logs/app.log',
            ]],
        ],
        'errorHandler' => ['errorAction' => 'site/error'],
        'urlManager' => [
            'enablePrettyUrl' => true,
            'showScriptName'  => false,
            'rules' => [
                ''                                   => 'site/index',
                'login'                              => 'site/login',
                'register'                           => 'site/register',
                'forgot-password'                    => 'site/forgot-password',
                'reset-password/<token>'             => 'site/reset-password',
                'logout'                             => 'site/logout',
                'error'                              => 'site/error',
                // Admin
                'admin/dashboard'                    => 'admin/dashboard',
                'admin/analytics'                    => 'admin/analytics',
                'admin/map'                          => 'admin/map',
                'admin/vendors'                      => 'admin/vendors',
                'admin/vendors/view'                 => 'admin/vendor-view',
                'admin/vendors/<id:\d+>'             => 'admin/vendor-view',
                'admin/vendors/<id:\d+>/edit'        => 'admin/vendor-edit',
                'admin/vendors/<id:\d+>/suspend'     => 'admin/vendor-suspend',
                'admin/vendors/<id:\d+>/delete'      => 'admin/vendor-delete',
                'admin/users'                        => 'admin/users',
                'admin/users/create'                 => 'admin/user-edit',
                'admin/users/<id:\d+>'               => 'admin/user-view',
                'admin/users/<id:\d+>/edit'          => 'admin/user-edit',
                'admin/users/<id:\d+>/suspend'       => 'admin/user-suspend',
                'admin/providers'                    => 'admin/providers',
                'admin/providers/<id:\d+>/approve'   => 'admin/approve-provider',
                'admin/providers/<id:\d+>/reject'    => 'admin/reject-provider',
                'admin/orders'                       => 'admin/orders',
                'admin/orders/<id:\d+>'              => 'admin/order-view',
                'admin/order-view/<id:\d+>'          => 'admin/order-view',
                'admin/payments'                     => 'admin/payments',
                'admin/listings'                     => 'admin/listings',
                'admin/categories'                   => 'admin/categories',
                'admin/category-create'              => 'admin/category-create',
                'admin/category-edit/<id:\d+>'       => 'admin/category-edit',
                'admin/category-delete/<id:\d+>'     => 'admin/category-delete',
                'admin/categories/create'            => 'admin/category-create',
                'admin/categories/<id:\d+>/edit'     => 'admin/category-edit',
                'admin/categories/<id:\d+>/delete'   => 'admin/category-delete',
                'admin/reviews'                      => 'admin/reviews',
                'admin/reviews/<id:\d+>/toggle'      => 'admin/review-toggle',
                'admin/reviews/<id:\d+>/delete'      => 'admin/review-delete',
                'admin/earnings'                     => 'admin/earnings',
                'admin/subscriptions'                => 'admin/subscriptions',
                'admin/subscriptions/<id:\d+>/renew' => 'admin/subscription-renew',
                'admin/subscriptions/<id:\d+>/cancel'=> 'admin/subscription-cancel',
                'admin/payouts'                      => 'admin/payouts',
                'admin/invoices'                     => 'admin/invoices',
                'admin/messages'                     => 'admin/messages',
                'admin/notifications'                => 'admin/notifications',
                'admin/notifications/mark-all-read'  => 'admin/notifications-mark-all-read',
                'admin/settings'                     => 'admin/settings',
                // Provider area
                'dashboard'                          => 'provider/dashboard',
                'my-listings'                        => 'provider/listings',
                'my-listings/create'                 => 'provider/create-listing',
                'my-listings/<id:\d+>/update'        => 'provider/edit-listing',
                'my-listings/<id:\d+>/delete'        => 'provider/delete-listing',
                'my-orders'                          => 'provider/orders',
                'my-orders/<id:\d+>/accept'          => 'provider/accept-order',
                'my-orders/<id:\d+>/complete'        => 'provider/complete-order',
                'subscription'                       => 'provider/subscription',
                'subscription/purchase/<planId:\d+>' => 'provider/subscribe-plan',
                'earnings'                           => 'provider/earnings',
                'profile'                            => 'provider/profile',
                'provider/dashboard'                 => 'provider/dashboard',
                'provider/listings'                  => 'provider/listings',
                'provider/create-listing'            => 'provider/create-listing',
                'provider/edit-listing'              => 'provider/edit-listing',
                'provider/delete-listing'            => 'provider/delete-listing',
                'provider/orders'                    => 'provider/orders',
                'provider/accept-order'              => 'provider/accept-order',
                'provider/complete-order'            => 'provider/complete-order',
                'provider/subscription'              => 'provider/subscription',
                'provider/subscribe-plan/<planId:\d+>' => 'provider/subscribe-plan',
                'provider/earnings'                  => 'provider/earnings',
                'provider/profile'                   => 'provider/profile',
                'provider/reviews'                   => 'provider/reviews',
                'provider/settings'                  => 'provider/settings',
                'provider/messages'                  => 'provider/messages',
                'provider/payouts'                   => 'provider/payouts',
                'provider/analytics'                => 'provider/analytics',
                'provider/notifications'             => 'provider/notifications',
                'provider/notifications/mark-all-read' => 'provider/mark-all-read',
                'provider/order-view/<id:\d+>'       => 'provider/order-view',
                'provider/orders/<id:\d+>'           => 'provider/order-view',
            ],
        ],
    ],
    'params' => $params,
];
